### ISSUE TITLE
Modify or remove the error message that occurs when the user has not used the proper function name in unittest

### ISSUE THREAD

**Issue by tababbitt** [kylekyle/it105#11]
Prior to coding, if there is a unittest to compare the return of a cadet created function with expected values, a error message is displayed. 

![image](https://user-images.githubusercontent.com/24895869/41565943-1abab82a-7327-11e8-8646-97693de6d4b8.png)

Unittest code

```python
self.assertAlmostEqual(main.areaOfEqTriangle(1.0), 0.43301, 3, "Ensure your formula is correct")
```

**Comment by tababbitt** [comment]
It appears that the unittest runs first thing prior to a student clicking the check mark. A delay to not check until the student pushes the button could assist.

**Comment by kylekyle** [comment]
Not sure if this is still an issue. Feel free to reopen if it is.
